### ISSUE TITLE
Example projects not loading

### ISSUE THREAD

**Issue by Phenomena3** [4ian/GDevelop#1290]
## Describe the bug
Some example projects on the wiki are empty or not loading, specifically the Dialogue Tree example. The forum thread below contains a report of other links to empty projects, but doesn't provide details about every link affected.

https://forum.gdevelop-app.com/t/what-happened-to-the-dialogue-tree-example/21471/2

Please double check that the bug is not already reported in the issues list. ✔✔

## To Reproduce
1. Go to https://editor.gdevelop-app.com/?project=example://dialogue-tree-with-yarn
2. See empty project as shown in the screenshot attached below and on the forum thread.

![yarnex](https://user-images.githubusercontent.com/45985516/68996320-660c7400-0866-11ea-9621-6b832eb1feee.png)

* Please include a link to a game if possible! **N/A**
* If applicable, add screenshots to help explain your problem. ✔

## Other details
* Include any OS/browser version/smartphone that you're using

Windows 8.1 laptop
> Google Chrome is up to date
> Version 78.0.3904.97 (Official Build) (64-bit)

* Which version of GDevelop are you using? The desktop app or the web-app?

I use the latest release of the desktop app, but this is regarding the web-app.

* Add any other context about the problem here. **N/A**

**Comment by blurymind** [comment]
Strange :) it works for me even on a smartphone.. might have to make the
demo more touch input friendly though

Do you get any error messages? If you open the console with Ctrl+shift+i
any warnings or errors?

**Comment by Phenomena3** [comment]
Strange indeed. No error messages or warnings at all.

![yarnex2](https://user-images.githubusercontent.com/45985516/69002938-61c47300-08c7-11ea-99cf-418414d0191b.png)

Now that you mention mobile, I have the same issue with my Android,

**Comment by blurymind** [comment]
I think a recent change broke direct links to demos

**Comment by 4ian** [comment]
My bad is a regression since I added Google Drive on the web-app 🤦🏻‍♂️
Will fix that soon!

**Comment by blurymind** [comment]
In the meantime the demo can still be opened if you manually find it in the
new project dialog. Just search for dialog tree when you create a new
project

**Comment by 4ian** [comment]
Fixed :) Thanks for reporting this!

**Comment by Phenomena3** [comment]
I may have to clear my browser cache because it still doesn't work for me with the web app.

Meanwhile, I can use the included demo per blurymind's suggestion :) Thanks!

**Comment by 4ian** [comment]
The web-app being a "Progressive Web App", the code and some assets are indeed cached on your computer/tablet/phone for faster startup time (and resilience against losing network access). You can also: open the web-app and give it a bit of time for it to download the update in the background. When it's downloaded, it will be updated after you close all the tabs having the web-app opened.

Or you can clear your entirer browser cache or the cache for editor.gdevelop-app.com ;)
In the future, a notification will be shown in the bottom of the screen to tell you that the web-app can be updated if you close tabs and reopen it.
