### ISSUE TITLE
Empty project file 

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1813]
We have 3 bug reports in less than two weeks about a zero-byte json project file, so I'll dare say something is wrong with beta 94/95.

[First report](https://forum.gdevelop-app.com/t/solved-project-stopped-opening/25371).
[Second report](https://forum.gdevelop-app.com/t/corrupt-gd5-file-heeeelp/25616).
[Third report](https://forum.gdevelop-app.com/t/project-suddenly-json-0-bytes/25683/8).

That's an awful bug, and we should add a big flashing warning somewhere or add some safety measure until this has been figured out. 😕

**Comment by PascalLadalle** [comment]
New report on the Discord (channel #general ) : https://pastebin.com/rX3eWc9C
Autosave file (two weeks old, although it shouldn't be):
[aaaa.json.autosave.zip](https://github.com/4ian/GDevelop/files/4771535/aaaa.json.autosave.zip)

**Comment by 4ian** [comment]
I fail to see what could trigger this but yeah it's worrying. I've added a fix that checks if the project is trying to be saved as an empty string (0 byte), and in this case to abort the save. 

If you any hypothesis on why this could happen (previous bug/crash that was dismissed that could put the software in an invalid state, pressing the save shortcut too much, anything!), let me know.

**Comment by 4ian** [comment]
> two weeks old, although it shouldn't be

Sadly the preview has a bug and was no triggering autosave in beta 95 :/ Fixed that, I'll try to release a new version soon.

**Comment by PascalLadalle** [comment]
Strange coincidence, no? A case of Murphy's law? 😀 
I asked many questions on the Discord, but was unable to get anything conclusive. He opened his project, worked on his double jump without previewing, without exporting, closed GDevelop, reopened a few hours later and bam.
I'm wondering, though. The first time, people get a "file is malformed", and the second time they try, they get a different message ("invalid file" or else, I forgot).
Any chance this could be a hint? Like the json being cleaned empty (perhaps cleaned not during _saving_, but during _loading_) because of a malformation caused by a forgotten or extra character somewhere (backslash, quotes...).
Could there be a problem with whatever compares the json to the autosave?
Wild guesses... just in case 😊

**Comment by 4ian** [comment]
I've published beta 96: https://github.com/4ian/GDevelop/releases/tag/v5.0.0-beta96
with what I hope is a protection against 0 bytes file and fixed autosave (this will at least reduce a bit the problem..).
As there were internal changes, can you check it out and let me know if everything looks alright?  I'll activate the autoupdate later, I just don't want to rush into releasing a new version if there is something I missed :)

**Comment by PascalLadalle** [comment]
Looks okay so far. The only bug I caught is that the actual ladder speed is ~150 when the setting is at 0 (values of 0.1 and 1 work fine).

**Comment by arthuro555** [comment]
> with what I hope is a protection against 0 bytes file and fixed autosave (this will at least reduce a bit the problem..).

I still see the bug being reported. Potential fixes:
1. The string is not empty so we should check for a minimal length not for `== ''`
2. It tries to save multiples times at once (some people spam Ctrl-S) so there is some failure while accessing the file multiple times. We should add some sort of lock that prevents saving while the current saving process isn't finished.
3. The current electron version may have a broken fs module and bumping electron could potentially fix it (Just a thought didn't actually research if electron ever had that bug)

**Comment by 4ian** [comment]
> It tries to save multiples times at once (some people spam Ctrl-S) so there is some failure while accessing the file multiple times. We should add some sort of lock that prevents saving while the current saving process isn't finished.

It seems to be a very probable cause of the bug.
I've opened #1890 to fix this. Precisely, before adding the "protection against spamming Ctrl+S", I added a check for the proper content of the file written on disk (so that the save is considered failed if `writeFile` is finished, but then when reading the file the content is not the same as the one saved).

I've found that when spamming Ctrl+S/Cmd+S, some of these checks where failing because the file was empty. I think this is due to the way writeFile works, it's not "atomic". See this [interesting answer on SO](https://stackoverflow.com/a/39060492).

Now with the concurrent save protection I'm pretty sure this bug would vanish. Better, with the additional check for the file content, if for some reason the written file is not exactly what should have been written, the whole save is considered as failed - meaning that the user will see an error message. The user can then just save again and this will probably work.
