### ISSUE TITLE
Poor memory management when changing scenes causing permanent memory increase

### ISSUE THREAD

**Issue by ZachjuKamashi** [4ian/GDevelop#5921]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

There is a permanent memory increase after changing scenes with regarding events which can result in very high RAM usage in certain cases, enough for the project to run out of memory and even crash devices.

Here is a video showcasing how the memory usage performs with this test project.

https://github.com/4ian/GDevelop/assets/98941240/a9382f52-0431-4305-a4c2-8a20371108be

And here is the project file

[Memory_leak-iter3.zip](https://github.com/4ian/GDevelop/files/13397463/Memory_leak-iter3.zip)

### Steps to reproduce

Instructions are within the Project

### GDevelop platform

Desktop, Web, Mobile

### GDevelop version

5.3.180

### Platform info

Windows 10 Enterprise LTSC 21H2 OS Build 19044.1288

**Comment by D8H** [comment]
This is probably because the generated code is clearing object lists before the events instead of after them so some instances stays in memory until the scene is run again.

**Comment by ZachjuKamashi** [comment]
@D8H It's been half a year, are there any updates on solving this issue?

**Comment by 4ian** [comment]
Sorry for the delay on this, this should have been fixed in https://github.com/4ian/GDevelop/pull/6913 and fixed since version 5.4.210. 

Let me know if there is still a suspicious behavior from the memory. Note that in JS memory may takes some time to be reclaimed by the garbage collector (a garbage collection event must happen), but in theory a scene that is ended should now not increase memory usage.

**Comment by zeating** [comment]
definitely not fixed 
https://forum.gdevelop.io/t/my-game-freezes-when-loading-between-scenes/54062/6

**Comment by ZachjuKamashi** [comment]
> definitely not fixed https://forum.gdevelop.io/t/my-game-freezes-when-loading-between-scenes/54062/6

Does the Test project I provided here still result with the memory usage increase? I use an older version of GDevelop so I am unable to easily test
