### ISSUE TITLE
List of expressions starts at the bottom of the list

### ISSUE THREAD

**Issue by BWPanda** [4ian/GDevelop#858]
## Describe the bug
When clicking the sigma (summation) button to enter an expression, variable, etc., the list that is displayed starts off scrolled all the way at the bottom. You have to scroll up to not only see the more commonly-used items, but also the helpful search bar.

It should start at the top when opened.

## To Reproduce
See this example:
![peek 2019-01-09 21-08](https://user-images.githubusercontent.com/2385329/50922292-d41c2980-1452-11e9-963f-06c56aa0bfcb.gif)

**Comment by 4ian** [comment]
Fixed for next version by switching back to the default opening animation for the list popover - so that search field/list is displayed from the top :)

**Comment by BWPanda** [comment]
@4ian This is still an issue in beta64 - the sigma/summation/expression button list opens at the bottom and you have to scroll up to see the top/search option...

**Comment by 4ian** [comment]
Damn, I was sure it was working well. Must be something else then
