### ISSUE TITLE
[$5 bounty] Text object at wrong position (and moves!)

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#975]
## Describe the bug
A picture is worth a thousand words... well I have four!
Please look on each picture at the position of "Score :" in the editor on the left, and in preview on the right.
All fine here:
![nobug1](https://user-images.githubusercontent.com/25978830/54392026-d7c46a80-46a6-11e9-89c0-cca7db8079cb.jpg)
Score is higher than 10, still fine.
![nobug1b](https://user-images.githubusercontent.com/25978830/54392034-dbf08800-46a6-11e9-90e6-2443f1c74c50.jpg)
Text object has been rotated 90°.
![bug1](https://user-images.githubusercontent.com/25978830/54392038-df840f00-46a6-11e9-80ef-e5a9082ed617.jpg)
Score is higher than 10.
![bug1b](https://user-images.githubusercontent.com/25978830/54392045-e27eff80-46a6-11e9-9da2-910e6de2887e.png)

## To Reproduce
Place a Text object on an external layout.
Rotate the object.
Load the layout in a scene.

## Other details
GD beta 65, Windows 10

**Comment by PascalLadalle** [comment]
Can you not reproduce this issue?

**Comment by KinkGD** [comment]
Can you provide an example file ? Because i tried few things but can reproduce... 
You seems to use the default font ? No breakline or width limitation on text field ?

**Comment by PascalLadalle** [comment]
Yes @KinkGD , default font and nothing fancy, rotation only.
I just tried the following, it reproduces the issue for me: Create a new game using the default platformer example, rotate the score text 90° and place it next to the coin icon.
Grab coins and watch the text move.
![image](https://user-images.githubusercontent.com/25978830/55343638-cd2e1180-54ab-11e9-9c2f-6e84508109a9.png)

**Comment by 4ian** [comment]
So this is surprising to say the least but per se "working as intended". The thing is that the position of the object is determined by its origin point on the top left BUT the center, used for rotation, is the middle of the object.
This means that when the text grow, the center moves to the right, so the object also seems to move to the right when it's rotated.

A solution could be to allow to specify the origin point to be the center, but not sure if there is a better way.

**Comment by PascalLadalle** [comment]
> The thing is that the position of the object is determined by its origin point on the top left 

I placed a marker on ScoreX/Y(), see what happens:
![image](https://user-images.githubusercontent.com/25978830/55349548-47659280-54ba-11e9-94c6-3599afbfae07.png)

The second position doesn't look like a top-left corner 😬 (the position was updated, of course)

> This means that when the text grow, the center moves to the right, so the object also seems to move to the right when it's rotated.

But the object is rotated, so the center should in fact move down, right?

Am I right to assume that this issue is related to what I will call a weirdity, not to call it a bug:
![image](https://user-images.githubusercontent.com/25978830/55351542-ec826a00-54be-11e9-8634-c7690731d174.png)

**Comment by Lizard-13** [comment]
![RotatedText](https://user-images.githubusercontent.com/9782647/55575508-609e5700-56e5-11e9-922a-f935fd384c25.png)
That's why ;)

The non-rotated object selection mask in the IDE is a bad design that comes from the ice era :D

**Comment by Bouh** [comment]
@PascalLadalle it is solved by beta 110?

[From patch note](https://github.com/4ian/GDevelop/releases/tag/v5.0.0-beta110):
> Fix sprite objects updating their displayed image one frame too late:
This fixes some "flickering" when a sprite is just created, when a scene is changed or when external layout objects are created on a scene.
This also fix objects that are not at the proper size/position/angle just after being created in events.

**Comment by PascalLadalle** [comment]
Nope, issue is still there, I'm afraid.
![image](https://user-images.githubusercontent.com/25978830/120081434-f4012600-c0bd-11eb-90b7-a2c3a7d55a98.png)![image](https://user-images.githubusercontent.com/25978830/120081440-ff545180-c0bd-11eb-89cc-146dd28f5659.png)

**Comment by Bouh** [comment]
Can you drop the project here, please?

**Comment by PascalLadalle** [comment]
Default platformer with rotated score text:
[My project28.zip](https://github.com/4ian/GDevelop/files/6565320/My.project28.zip)

**Comment by Bouh** [comment]
Here another project with all types of text objects, all have their own issues when the angle is different than zero.
[Project_example.zip](https://github.com/4ian/GDevelop/files/6566232/Project_example.zip)

**Comment by Bouh** [comment]
There is 3 type of text objects with the same issue, I offer $25 reward on fixing these bugs.

**Comment by Bouh** [comment]
In addition to this issue, [I link this thread on the forum](https://forum.gdevelop.io/t/rotating-a-text-object-messes-up-its-coordinates/41260/9).

**Comment by cinemaaiproductions-dev** [comment]
I'd like to work on this. Looking into it now.

Payable to Cashapp: $mindingurbusiness101

**Comment by 2bf** [comment]
Opened PR #8620 for this: https://github.com/4ian/GDevelop/pull/8620

It refreshes the Text renderer position after the Pixi text metrics are recalculated on string updates, matching the existing BBText/BitmapText renderer behavior and targeting the rotated dynamic text movement described here.
